"""
inference/mock_backend.py
-------------------------
Simulated backend for testing and development *without* a live LLM.

⚠️  Responses are entirely synthetic.
    They are NOT generated by any real language model.
    Do NOT treat timing figures as representative of real LLM latency.

The ``elapsed_ms`` field on the returned :class:`~inference.result.InferenceResult`
measures only the overhead of this mock implementation (dictionary lookup,
object construction).  It will be on the order of microseconds, which is
orders of magnitude faster than real inference.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone

from inference.backend import InferenceBackend
from inference.config import ModelConfig, ModelSize
from inference.result import InferenceResult

# ---------------------------------------------------------------------------
# Canned responses — clearly labelled as synthetic
# ---------------------------------------------------------------------------

_SYNTHETIC_RESPONSES: dict[ModelSize, str] = {
    ModelSize.SMALL: (
        "[SYNTHETIC] Short answer from the small-tier mock. "
        "No real model was consulted."
    ),
    ModelSize.MEDIUM: (
        "[SYNTHETIC] Medium-length answer from the medium-tier mock. "
        "This text was generated by MockBackend, not by an LLM."
    ),
    ModelSize.LARGE: (
        "[SYNTHETIC] Detailed answer from the large-tier mock. "
        "This is placeholder text produced by MockBackend for testing purposes. "
        "It does not reflect the capabilities or output style of any real model."
    ),
}


class MockBackend(InferenceBackend):
    """Deterministic, in-process backend that returns canned responses.

    Parameters
    ----------
    always_available:
        When ``False``, :meth:`is_available` returns ``False``, which is
        useful for testing error-handling logic in the router.
    custom_responses:
        Optional mapping from :class:`~inference.config.ModelSize` to a
        custom response string.  Useful for per-test determinism.
    """

    NAME = "mock"

    def __init__(
        self,
        always_available: bool = True,
        custom_responses: dict[ModelSize, str] | None = None,
    ) -> None:
        self._available = always_available
        self._responses: dict[ModelSize, str] = {
            **_SYNTHETIC_RESPONSES,
            **(custom_responses or {}),
        }

    # ------------------------------------------------------------------
    # InferenceBackend interface
    # ------------------------------------------------------------------

    @property
    def name(self) -> str:
        return self.NAME

    def infer(self, prompt: str, config: ModelConfig) -> InferenceResult:
        """Return a synthetic response.

        Timing
        ------
        ``elapsed_ms`` reflects only mock overhead (dictionary lookup +
        object construction).  It is **not** representative of real LLM
        inference latency.
        """
        if not prompt or not prompt.strip():
            raise ValueError("prompt must not be empty")

        t0 = time.perf_counter()

        # Retrieve the canned text for this tier
        response_text = self._responses.get(
            config.size,
            f"[SYNTHETIC] No canned response registered for size {config.size!r}.",
        )
        # Prefix with the model id so callers can see which config was used
        response = f"[mock:{config.model_id}] {response_text}"

        elapsed_ms = (time.perf_counter() - t0) * 1_000

        return InferenceResult(
            model_id=config.model_id,
            prompt=prompt,
            response=response,
            elapsed_ms=elapsed_ms,
            timestamp=datetime.now(tz=timezone.utc),
            backend=self.NAME,
            is_cached=False,
            metadata={"synthetic": True, "tier": config.size.value},
        )

    def is_available(self) -> bool:
        """Return the availability state set at construction time."""
        return self._available
